// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Diplom
{
    public partial class MLModel
    {
        /// <summary>
        /// model input class for MLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Open")]
            public float Open { get; set; }

            [ColumnName(@"Close")]
            public float Close { get; set; }

            [ColumnName(@"High")]
            public float High { get; set; }

            [ColumnName(@"Low")]
            public float Low { get; set; }

            [ColumnName(@"Volume")]
            public float Volume { get; set; }

            [ColumnName(@"Open2")]
            public float Open2 { get; set; }

            [ColumnName(@"Close2")]
            public float Close2 { get; set; }

            [ColumnName(@"High2")]
            public float High2 { get; set; }

            [ColumnName(@"Low2")]
            public float Low2 { get; set; }

            [ColumnName(@"Volume2")]
            public float Volume2 { get; set; }

            [ColumnName(@"Open3")]
            public float Open3 { get; set; }

            [ColumnName(@"Close3")]
            public float Close3 { get; set; }

            [ColumnName(@"High3")]
            public float High3 { get; set; }

            [ColumnName(@"Low3")]
            public float Low3 { get; set; }

            [ColumnName(@"Volume3")]
            public float Volume3 { get; set; }

            [ColumnName(@"Open4")]
            public float Open4 { get; set; }

            [ColumnName(@"Close4")]
            public float Close4 { get; set; }

            [ColumnName(@"High4")]
            public float High4 { get; set; }

            [ColumnName(@"Low4")]
            public float Low4 { get; set; }

            [ColumnName(@"Volume4")]
            public float Volume4 { get; set; }

            [ColumnName(@"Open5")]
            public float Open5 { get; set; }

            [ColumnName(@"Close5")]
            public float Close5 { get; set; }

            [ColumnName(@"High5")]
            public float High5 { get; set; }

            [ColumnName(@"Low5")]
            public float Low5 { get; set; }

            [ColumnName(@"Volume5")]
            public float Volume5 { get; set; }

            [ColumnName(@"Open6")]
            public float Open6 { get; set; }

            [ColumnName(@"Close6")]
            public float Close6 { get; set; }

            [ColumnName(@"High6")]
            public float High6 { get; set; }

            [ColumnName(@"Low6")]
            public float Low6 { get; set; }

            [ColumnName(@"Volume6")]
            public float Volume6 { get; set; }

            [ColumnName(@"Open7")]
            public float Open7 { get; set; }

            [ColumnName(@"Close7")]
            public float Close7 { get; set; }

            [ColumnName(@"High7")]
            public float High7 { get; set; }

            [ColumnName(@"Low7")]
            public float Low7 { get; set; }

            [ColumnName(@"Volume7")]
            public float Volume7 { get; set; }

            [ColumnName(@"Open8")]
            public float Open8 { get; set; }

            [ColumnName(@"Close8")]
            public float Close8 { get; set; }

            [ColumnName(@"High8")]
            public float High8 { get; set; }

            [ColumnName(@"Low8")]
            public float Low8 { get; set; }

            [ColumnName(@"Volume8")]
            public float Volume8 { get; set; }

            [ColumnName(@"Open9")]
            public float Open9 { get; set; }

            [ColumnName(@"Close9")]
            public float Close9 { get; set; }

            [ColumnName(@"High9")]
            public float High9 { get; set; }

            [ColumnName(@"Low9")]
            public float Low9 { get; set; }

            [ColumnName(@"Volume9")]
            public float Volume9 { get; set; }

            [ColumnName(@"Open10")]
            public float Open10 { get; set; }

            [ColumnName(@"Close10")]
            public float Close10 { get; set; }

            [ColumnName(@"High10")]
            public float High10 { get; set; }

            [ColumnName(@"Low10")]
            public float Low10 { get; set; }

            [ColumnName(@"Volume10")]
            public float Volume10 { get; set; }

            [ColumnName(@"Open11")]
            public float Open11 { get; set; }

            [ColumnName(@"Close11")]
            public float Close11 { get; set; }

            [ColumnName(@"High11")]
            public float High11 { get; set; }

            [ColumnName(@"Low11")]
            public float Low11 { get; set; }

            [ColumnName(@"Volume11")]
            public float Volume11 { get; set; }

            [ColumnName(@"Open12")]
            public float Open12 { get; set; }

            [ColumnName(@"Close12")]
            public float Close12 { get; set; }

            [ColumnName(@"High12")]
            public float High12 { get; set; }

            [ColumnName(@"Low12")]
            public float Low12 { get; set; }

            [ColumnName(@"Volume12")]
            public float Volume12 { get; set; }

            [ColumnName(@"Open13")]
            public float Open13 { get; set; }

            [ColumnName(@"Close13")]
            public float Close13 { get; set; }

            [ColumnName(@"High13")]
            public float High13 { get; set; }

            [ColumnName(@"Low13")]
            public float Low13 { get; set; }

            [ColumnName(@"Volume13")]
            public float Volume13 { get; set; }

            [ColumnName(@"Open14")]
            public float Open14 { get; set; }

            [ColumnName(@"Close14")]
            public float Close14 { get; set; }

            [ColumnName(@"High14")]
            public float High14 { get; set; }

            [ColumnName(@"Low14")]
            public float Low14 { get; set; }

            [ColumnName(@"Volume14")]
            public float Volume14 { get; set; }

            [ColumnName(@"Open15")]
            public float Open15 { get; set; }

            [ColumnName(@"Close15")]
            public float Close15 { get; set; }

            [ColumnName(@"High15")]
            public float High15 { get; set; }

            [ColumnName(@"Low15")]
            public float Low15 { get; set; }

            [ColumnName(@"Volume15")]
            public float Volume15 { get; set; }

            [ColumnName(@"Open16")]
            public float Open16 { get; set; }

            [ColumnName(@"Close16")]
            public float Close16 { get; set; }

            [ColumnName(@"High16")]
            public float High16 { get; set; }

            [ColumnName(@"Low16")]
            public float Low16 { get; set; }

            [ColumnName(@"Volume16")]
            public float Volume16 { get; set; }

            [ColumnName(@"Open17")]
            public float Open17 { get; set; }

            [ColumnName(@"Close17")]
            public float Close17 { get; set; }

            [ColumnName(@"High17")]
            public float High17 { get; set; }

            [ColumnName(@"Low17")]
            public float Low17 { get; set; }

            [ColumnName(@"Volume17")]
            public float Volume17 { get; set; }

            [ColumnName(@"Open18")]
            public float Open18 { get; set; }

            [ColumnName(@"Close18")]
            public float Close18 { get; set; }

            [ColumnName(@"High18")]
            public float High18 { get; set; }

            [ColumnName(@"Low18")]
            public float Low18 { get; set; }

            [ColumnName(@"Volume18")]
            public float Volume18 { get; set; }

            [ColumnName(@"Open19")]
            public float Open19 { get; set; }

            [ColumnName(@"Close19")]
            public float Close19 { get; set; }

            [ColumnName(@"High19")]
            public float High19 { get; set; }

            [ColumnName(@"Low19")]
            public float Low19 { get; set; }

            [ColumnName(@"Volume19")]
            public float Volume19 { get; set; }

            [ColumnName(@"Open20")]
            public float Open20 { get; set; }

            [ColumnName(@"Close20")]
            public float Close20 { get; set; }

            [ColumnName(@"High20")]
            public float High20 { get; set; }

            [ColumnName(@"Low20")]
            public float Low20 { get; set; }

            [ColumnName(@"Volume20")]
            public float Volume20 { get; set; }

            [ColumnName(@"Open21")]
            public float Open21 { get; set; }

            [ColumnName(@"Close21")]
            public float Close21 { get; set; }

            [ColumnName(@"High21")]
            public float High21 { get; set; }

            [ColumnName(@"Low21")]
            public float Low21 { get; set; }

            [ColumnName(@"Volume21")]
            public float Volume21 { get; set; }

            [ColumnName(@"Open22")]
            public float Open22 { get; set; }

            [ColumnName(@"Close22")]
            public float Close22 { get; set; }

            [ColumnName(@"High22")]
            public float High22 { get; set; }

            [ColumnName(@"Low22")]
            public float Low22 { get; set; }

            [ColumnName(@"Volume22")]
            public float Volume22 { get; set; }

            [ColumnName(@"Open23")]
            public float Open23 { get; set; }

            [ColumnName(@"Close23")]
            public float Close23 { get; set; }

            [ColumnName(@"High23")]
            public float High23 { get; set; }

            [ColumnName(@"Low23")]
            public float Low23 { get; set; }

            [ColumnName(@"Volume23")]
            public float Volume23 { get; set; }

            [ColumnName(@"Open24")]
            public float Open24 { get; set; }

            [ColumnName(@"Close24")]
            public float Close24 { get; set; }

            [ColumnName(@"High24")]
            public float High24 { get; set; }

            [ColumnName(@"Low24")]
            public float Low24 { get; set; }

            [ColumnName(@"Volume24")]
            public float Volume24 { get; set; }

            [ColumnName(@"Open25")]
            public float Open25 { get; set; }

            [ColumnName(@"Close25")]
            public float Close25 { get; set; }

            [ColumnName(@"High25")]
            public float High25 { get; set; }

            [ColumnName(@"Low25")]
            public float Low25 { get; set; }

            [ColumnName(@"Volume25")]
            public float Volume25 { get; set; }

            [ColumnName(@"Open26")]
            public float Open26 { get; set; }

            [ColumnName(@"Close26")]
            public float Close26 { get; set; }

            [ColumnName(@"High26")]
            public float High26 { get; set; }

            [ColumnName(@"Low26")]
            public float Low26 { get; set; }

            [ColumnName(@"Volume26")]
            public float Volume26 { get; set; }

            [ColumnName(@"Open27")]
            public float Open27 { get; set; }

            [ColumnName(@"Close27")]
            public float Close27 { get; set; }

            [ColumnName(@"High27")]
            public float High27 { get; set; }

            [ColumnName(@"Low27")]
            public float Low27 { get; set; }

            [ColumnName(@"Volume27")]
            public float Volume27 { get; set; }

            [ColumnName(@"Open28")]
            public float Open28 { get; set; }

            [ColumnName(@"Close28")]
            public float Close28 { get; set; }

            [ColumnName(@"High28")]
            public float High28 { get; set; }

            [ColumnName(@"Low28")]
            public float Low28 { get; set; }

            [ColumnName(@"Volume28")]
            public float Volume28 { get; set; }

            [ColumnName(@"Open29")]
            public float Open29 { get; set; }

            [ColumnName(@"Close29")]
            public float Close29 { get; set; }

            [ColumnName(@"High29")]
            public float High29 { get; set; }

            [ColumnName(@"Low29")]
            public float Low29 { get; set; }

            [ColumnName(@"Volume29")]
            public float Volume29 { get; set; }

            [ColumnName(@"Open30")]
            public float Open30 { get; set; }

            [ColumnName(@"Close30")]
            public float Close30 { get; set; }

            [ColumnName(@"High30")]
            public float High30 { get; set; }

            [ColumnName(@"Low30")]
            public float Low30 { get; set; }

            [ColumnName(@"Volume30")]
            public float Volume30 { get; set; }

            [ColumnName(@"Open31")]
            public float Open31 { get; set; }

            [ColumnName(@"Close31")]
            public float Close31 { get; set; }

            [ColumnName(@"High31")]
            public float High31 { get; set; }

            [ColumnName(@"Low31")]
            public float Low31 { get; set; }

            [ColumnName(@"Volume31")]
            public float Volume31 { get; set; }

            [ColumnName(@"Open32")]
            public float Open32 { get; set; }

            [ColumnName(@"Close32")]
            public float Close32 { get; set; }

            [ColumnName(@"High32")]
            public float High32 { get; set; }

            [ColumnName(@"Low32")]
            public float Low32 { get; set; }

            [ColumnName(@"Volume32")]
            public float Volume32 { get; set; }

            [ColumnName(@"Open33")]
            public float Open33 { get; set; }

            [ColumnName(@"Close33")]
            public float Close33 { get; set; }

            [ColumnName(@"High33")]
            public float High33 { get; set; }

            [ColumnName(@"Low33")]
            public float Low33 { get; set; }

            [ColumnName(@"Volume33")]
            public float Volume33 { get; set; }

            [ColumnName(@"Open34")]
            public float Open34 { get; set; }

            [ColumnName(@"Close34")]
            public float Close34 { get; set; }

            [ColumnName(@"High34")]
            public float High34 { get; set; }

            [ColumnName(@"Low34")]
            public float Low34 { get; set; }

            [ColumnName(@"Volume34")]
            public float Volume34 { get; set; }

            [ColumnName(@"Open35")]
            public float Open35 { get; set; }

            [ColumnName(@"Close35")]
            public float Close35 { get; set; }

            [ColumnName(@"High35")]
            public float High35 { get; set; }

            [ColumnName(@"Low35")]
            public float Low35 { get; set; }

            [ColumnName(@"Volume35")]
            public float Volume35 { get; set; }

            [ColumnName(@"Open36")]
            public float Open36 { get; set; }

            [ColumnName(@"Close36")]
            public float Close36 { get; set; }

            [ColumnName(@"High36")]
            public float High36 { get; set; }

            [ColumnName(@"Low36")]
            public float Low36 { get; set; }

            [ColumnName(@"Volume36")]
            public float Volume36 { get; set; }

            [ColumnName(@"Open37")]
            public float Open37 { get; set; }

            [ColumnName(@"Close37")]
            public float Close37 { get; set; }

            [ColumnName(@"High37")]
            public float High37 { get; set; }

            [ColumnName(@"Low37")]
            public float Low37 { get; set; }

            [ColumnName(@"Volume37")]
            public float Volume37 { get; set; }

            [ColumnName(@"Open38")]
            public float Open38 { get; set; }

            [ColumnName(@"Close38")]
            public float Close38 { get; set; }

            [ColumnName(@"High38")]
            public float High38 { get; set; }

            [ColumnName(@"Low38")]
            public float Low38 { get; set; }

            [ColumnName(@"Volume38")]
            public float Volume38 { get; set; }

            [ColumnName(@"Open39")]
            public float Open39 { get; set; }

            [ColumnName(@"Close39")]
            public float Close39 { get; set; }

            [ColumnName(@"High39")]
            public float High39 { get; set; }

            [ColumnName(@"Low39")]
            public float Low39 { get; set; }

            [ColumnName(@"Volume39")]
            public float Volume39 { get; set; }

            [ColumnName(@"Open40")]
            public float Open40 { get; set; }

            [ColumnName(@"Close40")]
            public float Close40 { get; set; }

            [ColumnName(@"High40")]
            public float High40 { get; set; }

            [ColumnName(@"Low40")]
            public float Low40 { get; set; }

            [ColumnName(@"Volume40")]
            public float Volume40 { get; set; }

            [ColumnName(@"Open41")]
            public float Open41 { get; set; }

            [ColumnName(@"Close41")]
            public float Close41 { get; set; }

            [ColumnName(@"High41")]
            public float High41 { get; set; }

            [ColumnName(@"Low41")]
            public float Low41 { get; set; }

            [ColumnName(@"Volume41")]
            public float Volume41 { get; set; }

            [ColumnName(@"Open42")]
            public float Open42 { get; set; }

            [ColumnName(@"Close42")]
            public float Close42 { get; set; }

            [ColumnName(@"High42")]
            public float High42 { get; set; }

            [ColumnName(@"Low42")]
            public float Low42 { get; set; }

            [ColumnName(@"Volume42")]
            public float Volume42 { get; set; }

            [ColumnName(@"Open43")]
            public float Open43 { get; set; }

            [ColumnName(@"Close43")]
            public float Close43 { get; set; }

            [ColumnName(@"High43")]
            public float High43 { get; set; }

            [ColumnName(@"Low43")]
            public float Low43 { get; set; }

            [ColumnName(@"Volume43")]
            public float Volume43 { get; set; }

            [ColumnName(@"Open44")]
            public float Open44 { get; set; }

            [ColumnName(@"Close44")]
            public float Close44 { get; set; }

            [ColumnName(@"High44")]
            public float High44 { get; set; }

            [ColumnName(@"Low44")]
            public float Low44 { get; set; }

            [ColumnName(@"Volume44")]
            public float Volume44 { get; set; }

            [ColumnName(@"Open45")]
            public float Open45 { get; set; }

            [ColumnName(@"Close45")]
            public float Close45 { get; set; }

            [ColumnName(@"High45")]
            public float High45 { get; set; }

            [ColumnName(@"Low45")]
            public float Low45 { get; set; }

            [ColumnName(@"Volume45")]
            public float Volume45 { get; set; }

            [ColumnName(@"Open46")]
            public float Open46 { get; set; }

            [ColumnName(@"Close46")]
            public float Close46 { get; set; }

            [ColumnName(@"High46")]
            public float High46 { get; set; }

            [ColumnName(@"Low46")]
            public float Low46 { get; set; }

            [ColumnName(@"Volume46")]
            public float Volume46 { get; set; }

            [ColumnName(@"Open47")]
            public float Open47 { get; set; }

            [ColumnName(@"Close47")]
            public float Close47 { get; set; }

            [ColumnName(@"High47")]
            public float High47 { get; set; }

            [ColumnName(@"Low47")]
            public float Low47 { get; set; }

            [ColumnName(@"Volume47")]
            public float Volume47 { get; set; }

            [ColumnName(@"Open48")]
            public float Open48 { get; set; }

            [ColumnName(@"Close48")]
            public float Close48 { get; set; }

            [ColumnName(@"High48")]
            public float High48 { get; set; }

            [ColumnName(@"Low48")]
            public float Low48 { get; set; }

            [ColumnName(@"Volume48")]
            public float Volume48 { get; set; }

            [ColumnName(@"Open49")]
            public float Open49 { get; set; }

            [ColumnName(@"Close49")]
            public float Close49 { get; set; }

            [ColumnName(@"High49")]
            public float High49 { get; set; }

            [ColumnName(@"Low49")]
            public float Low49 { get; set; }

            [ColumnName(@"Volume49")]
            public float Volume49 { get; set; }

            [ColumnName(@"Open50")]
            public float Open50 { get; set; }

            [ColumnName(@"Close50")]
            public float Close50 { get; set; }

            [ColumnName(@"High50")]
            public float High50 { get; set; }

            [ColumnName(@"Low50")]
            public float Low50 { get; set; }

            [ColumnName(@"Volume50")]
            public float Volume50 { get; set; }

            [ColumnName(@"Open51")]
            public float Open51 { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            public float Score { get; set; }
        }
        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
